//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoSocial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Pessoa = new HashSet<Pessoa>();
        }
    
        public string Id { get; set; }
        public string Especie { get; set; }
        public string Nome { get; set; }
        public string Peso { get; set; }
        public string Cor { get; set; }
        public string Idade { get; set; }
        public Nullable<System.DateTime> DataInclusao { get; set; }
        public Nullable<System.DateTime> DataAdocao { get; set; }
        public string DescricaoLocalEncontrado { get; set; }
        public Nullable<int> Status { get; set; }
        public string Informacoes { get; set; }
        public string Vacinas { get; set; }
    
        public virtual Vacinacao Vacinacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}
