//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoSocial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public string Id { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataInclusao { get; set; }
        public string Informacoes { get; set; }
        public string Endereco { get; set; }
        public string Contato { get; set; }
        public string Login { get; set; }
        public string AnimaisAdotados { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Contato Contato1 { get; set; }
        public virtual Endereco Endereco1 { get; set; }
        public virtual Login Login1 { get; set; }
    }
}
